version: "3.9"
services:
  sparkler:
    container_name: sparkler-dev
    build:
      dockerfile: sparkler-deployment/docker/Dockerfile.dev
      context: .
    ports:
      - 8983:8983
      - 4041:4041
    volumes:
      - type: bind
        source: .
        target: /data/sparkler-core
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.1
    ports:
      - 5601:5601